eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:schools
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8070
